id: I74994411
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:03.770027
last_modified: 2023-01-04 11:32:03.770044
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  DAAF:
    title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
    base_file: DAAF.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
